[tools]
atuin = "latest"
bat = "latest"
btop = "latest"
bun = "latest"
cloudflared = "latest"
cmake = "latest"
"aqua:openai/codex" = "latest"
delta = "latest"
eza = "latest"
fd = "10.3.0"
fzf = "latest"
gemini = "latest"
gh = "latest"
gum = "latest"
herdr = "latest"
jq = "latest"
lazygit = "latest"
neovim = "nightly"
node = "22"
opencode = "latest"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zig = "latest"
zoxide = "latest"
aichat = "latest"
